export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zsh_history"    # History filepath
export HISTSIZE=1024                       # Maximum events for internal history
export SAVEHIST=1024                       # Maximum events in history file

export EDITOR="vim"
export VISUAL="vim"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"